### ISSUE TITLE
Move CI to public TravisCI?, and/or add public CI badge

### ISSUE THREAD

**Issue by benbuckman** [Shyp/go-circle#10]
We currently have tests for this repo running on a private CircleCI instance.
This is a public repo, however, so we should move the tests to the more open-source-friendly TravisCI.

(The last build failed, FWIW, with the following errors)

```
# github.com/github/hub/github
/home/ubuntu/.go_workspace/src/github.com/github/hub/github/client.go:148: too many arguments in call to api.Commits
/home/ubuntu/.go_workspace/src/github.com/github/hub/github/client.go:148: not enough arguments in call to api.Commits(client.requestURL(url)).Patch
/home/ubuntu/.go_workspace/src/github.com/github/hub/github/client.go:169: too many arguments in call to api.Gists
/home/ubuntu/.go_workspace/src/github.com/github/hub/github/client.go:169: not enough arguments in call to api.Gists(client.requestURL(url)).Raw
/home/ubuntu/.go_workspace/src/github.com/github/hub/github/client.go:190: too many arguments in call to api.Repositories
/home/ubuntu/.go_workspace/src/github.com/github/hub/github/client.go:190: not enough arguments in call to api.Repositories(client.requestURL(url)).One
/home/ubuntu/.go_workspace/src/github.com/github/hub/github/client.go:230: too many arguments in call to api.Repositories
/home/ubuntu/.go_workspace/src/github.com/github/hub/github/client.go:230: not enough arguments in call to api.Repositories(client.requestURL(url)).Create

go test -v -race ./... returned exit code 2
```

**Comment by kevinburke** [comment]
I thought about this a while ago and my one hesitation was the irony of testing a CircleCI library using a competitor.

**Comment by kevinburke** [comment]
I'm not sure where the error is coming from, I'm using the latest version of github.com/github/hub locally and things are working fine.

**Comment by benbuckman** [comment]
Oh interesting, https://circleci.com/gh/Shyp/go-circle/73 is actually publicly accessibly. TIL! So I should just add a badge to the readme, we don't have to move it to Travis.

**Comment by benbuckman** [comment]
@kevinburke Should there be a circle.yml file, too?

**Comment by benbuckman** [comment]
(I guess we don't technically need one https://circleci.com/docs/language-go/)

**Comment by kevinburke** [comment]
> @kevinburke Should there be a circle.yml file, too?

Up to you

**Comment by kevinburke** [comment]
It's possible one of the dependencies here still has a Godeps file or something.

**Comment by benbuckman** [comment]
(Let's move this to https://github.com/Shyp/go-circle/issues/11)
