### ISSUE TITLE
Fix CircleCI build

### ISSUE THREAD

**Issue by benbuckman** [Shyp/go-circle#11]
Tests are passing locally, but failing on CI. (https://circleci.com/gh/Shyp/go-circle/75)

**Comment by benbuckman** [comment]
from @kevinburke https://github.com/Shyp/go-circle/issues/10#issuecomment-271958238:

> It's possible one of the dependencies here still has a Godeps file or something.

**Comment by benbuckman** [comment]
I'm going to add a circle.yml file, even though it's not strictly necessary.

**Comment by benbuckman** [comment]
@kevinburke Could it be related to using an older version (1.6 instead of 1.7)?
https://circleci.com/docs/language-go/

> The pre-installed version of Go depends on which image your build is using:

> Ubuntu 14.04 - Go v1.6.2
Ubuntu 12.04 - Go v1.5.3
Unlike some other languages on CircleCI, you would not specify the Go version in the machine section of circle.yml.

**Comment by benbuckman** [comment]
Actually we were on `Ubuntu 12.04 (Precise)`, I'll bump it up.

**Comment by kevinburke** [comment]
It's possible but unlikely unless github.com/github/hub is using different
versions of the source code based on different Go versions


--
Kevin Burke
925.271.7005 | kev.inburke.com

**Comment by benbuckman** [comment]
FWIW I'm still very new to Go, so I don't really understand what's going on.

**Comment by benbuckman** [comment]
Uh, it just passed... https://circleci.com/gh/Shyp/go-circle/78 ... @kevinburke did you fix something? All I changed between that build and the previous failing build was add a `pre` step to output `go version`.

**Comment by benbuckman** [comment]
Weird... re-running the previous build without the `pre` step, it fails again:
https://circleci.com/gh/Shyp/go-circle/79

:man_shrugging:

**Comment by benbuckman** [comment]
Anyway, I have no idea why, but it should pass now.
(cc @ianmdawson )

**Comment by benbuckman** [comment]
(This kind of seems like a bug in Circle...)

**Comment by benbuckman** [comment]
I just emailed them to report it.
