### ISSUE TITLE
`circle wait` hung

### ISSUE THREAD

**Issue by dylanpyle** [Shyp/go-circle#23]
Not sure the best way to debug this, but `circle wait` just hung indefinitely after the build completed:

```
Waiting for latest build on master to complete
Running (3s elapsed)
Running (14s elapsed)
Running (25s elapsed)
Running (36s elapsed)
Running (48s elapsed)
Running (58s elapsed)
Running (1m9s elapsed)
Running (1m20s elapsed)
Running (1m31s elapsed)
Running (1m41s elapsed)
Running (1m52s elapsed)
Running (2m3s elapsed)
Running (2m13s elapsed)
Running (2m24s elapsed)
Running (2m35s elapsed)
Running (2m40s elapsed)
Running (2m46s elapsed)
Running (2m52s elapsed)
Running (2m58s elapsed)
Running (3m3s elapsed)
Running (3m9s elapsed)
Running (3m15s elapsed)
Running (3m29s elapsed)
Running (3m35s elapsed)
Running (3m40s elapsed)
Running (3m48s elapsed)
Running (3m54s elapsed)
Running (4m0s elapsed)
Running (4m6s elapsed)
Running (4m12s elapsed)
```

... and then nothing

**Comment by kevinburke** [comment]
Huh, wild. Can you reproduce it or did it just do that once?

I've been working on switching over the client to use the client in github.com/kevinburke/rest, which lets you set DEBUG_HTTP_TRAFFIC=true to easily grab the HTTP traffic.

Also possible Circle's having a bad day.

**Comment by ianmdawson** [comment]
I've been seeing issues similar to that on my machine for a little while, it's definitely something I've been intending to look into. I'll try the DEBUG_HTTP_TRAFFIC flag. My machine doesn't give me stats at all when the build is running, it only seems to display the following indefinitely:
```
Waiting for latest build on expose-invoice-and-discount-for-shipments to complete
Latest build in Circle is 4bd078dc, waiting for 4bd078dc...
Latest build in Circle is 4bd078dc, waiting for 4bd078dc...
Latest build in Circle is 4bd078dc, waiting for 4bd078dc...
Latest build in Circle is 4bd078dc, waiting for 4bd078dc...
Latest build in Circle is 4bd078dc, waiting for 4bd078dc...
Latest build in Circle is 4bd078dc, waiting for 4bd078dc...
Latest build in Circle is 4bd078dc, waiting for 4bd078dc...
```

**Comment by dylanpyle** [comment]
@kevinburke I've only seen it once, but I only just added this step into our build script a few days ago, so the data set is pretty small. Will keep an eye out for future occurrences 👀

**Comment by kevinburke** [comment]
> Latest build in Circle is 4bd078dc, waiting for 4bd078dc...

that seems bad... :( want to file a separate thing and we can hunt that down?

**Comment by ianmdawson** [comment]
Strangely it doesn't seem to happen to anyone else (or they haven't mentioned it). I'll try to dig into what might be causing that for me this weekend.

**Comment by kevinburkeshyp** [comment]
maybe try reinstalling `circle` from tip - git pull origin master && go
install ./...


--
Kevin Burke
925.271.7005 | kev.inburke.com

**Comment by kevinburke** [comment]
(We should close this)
